### ISSUE TITLE
Yay!  This is awesome! what should I do with macneib/livedb-rethink?

### ISSUE THREAD

**Issue by macneib** [thejsj/livedb-rethinkdb#1]
Hi!  I'm really excited to see someone has written what looks like a feature complete livedb driver!
My driver is not feature complete, however to avoid confusion should we perhaps pool our resources?

**Comment by thejsj** [comment]
I think that'd be great! I'm not sure how complete this implementation is. I'm currently testing it with ShareJS and LiveDB. Perhaps we can start by seeing if there are any features we'd like to implement or are missing? I'd some feedback!

**Comment by macneib** [comment]
I'll have a look at the modules this week and see if there is anything I can offer.  Usually I try to stick close to rethinkdb javascript driver and avoid rethinkdbdash.  Even though I like rethinkdbdash better and it has everything I want.  The connection pool is really appealing.  I'm not sure how much overhead exists with setting up db connections for each operation.  Probably a lot, but not exactly sure.  Also I'm not sure whether query functionality is working or now.  The Derby.js/Racer team depend on that quite a bit so there won't be a lot of adoption until that works.  I'll let you know what I find!  
Cheers!

**Comment by thejsj** [comment]
1. 

I'd be more than willing to change from rethinkdb.js to rethinkdbdash if it would improve performance. It's actually not that much work. I might actually do that soon, because I'm using a modified version of rethinkdbdash. 
1. 

>  Also I'm not sure whether query functionality is working or now. 

Right now, it's passing all the tests from the original MongoDB livedb driver and it seems to work correctly with textareas and CodeMirror. I'll test it out with Derby.js to see how well it works. 

Let me know if you come across any issues or have any suggestions! Cheers!
